language: java

jdk:
  - openjdk15

sudo: true

env:
  global:
    - CODECOV_TOKEN="6491e1cf-95c4-49d6-aea2-7afb15395e7c"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -rail.id@stk-online.ru
    on_success: never # default: change
    on_failure: always # default: always